#!/usr/bin/env php
<?php

use BackBee\Installer\InstallerApplicationConfig;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__.'/../vendor/autoload.php';

$cli = new ConsoleApplication(new InstallerApplicationConfig());
$cli->run();

